### ISSUE TITLE
Search: 'Ghoul' gets less hits than 'Ghouls'

### ISSUE THREAD

**Issue by rremeaux** [AdventureLookup/AdventureLookup#130]
Just by logic 'Ghoul' should get at least as many results as 'Ghouls', being part of the latter search term. A few other terms show the same issue, e.g. Giant/s; others don't, e.g. Dragon/s or Spider/s. Weird.

**Comment by cmfcmf** [comment]
I think this has something to do with a *Ghoul* to be considered a typo for *Ghost* and the same for *Ghouls* -> *Ghosts*. I am guessing, but haven't yet confirmed, that both *Ghoul* and *Ghouls* will result in all adventures with Ghoul/Ghouls, but may include other adventures based *Ghost*/*Ghosts* or something.

Maybe we should work out how to configure ElasticSearch _analyzers_ to singularize search terms / adventure content and remove some of the spelling autocorrection.

**Comment by csams** [comment]
Which analyzers/stemmers are currently in use in production?

**Comment by cmfcmf** [comment]
Eeehm, good question. I never looked into it, so they should be the default ones that come with the fields. As you see in the reindex command, which destroys and recreates the index, we don't specify analyzers: 
https://github.com/AdventureLookup/AdventureLookup/blob/c2dc1db1ee057bd5ee8f9459b87030a036c869f5/src/AppBundle/Command/AppElasticsearchReindexCommand.php#L53-L70

**Comment by cmfcmf** [comment]
I figured out why 'ghouls' resulted in more results than 'ghoul': We use fuzzy searching, which allows the search engine to return adventures that contain terms that don' quite match what the user entered. Words that contain between 3 and 5 characters (like 'ghoul') will match words that are similar to 'ghoul' with one edited character ('ghoul' would match, for example, 'shoul', 'ghouls', 'ghool').

Words that contain more than 5 characters allow up to two edits to find similar words. That's why 'ghouls' matches 'ghoul', 'ghou', but also 'should' and many more. Pull request #308 mitigates the problem somewhat by now disallowing the search engine to change the first two characters of terms: 'ghouls' would now no longer match 'should'.

Once this change goes live (I hope soon), the search experience should be much better.

**Comment by cmfcmf** [comment]
This is now live :tada: 
- `ghoul` now has 173 search results 
- `ghouls` now has 196 search results
