### ISSUE TITLE
Better Record Formatting

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#156]
Check out the Tomb of Absythor for what I mean. If we put Common Monsters and Notable Items in two adjacent columns, we clean up a lot of the formatting.

**Comment by cmfcmf** [comment]
Pull request in #160, this is how it looks like (screenshot from my local test installation)
![image](https://user-images.githubusercontent.com/2145092/29262625-ab471072-80d5-11e7-964c-f39a0819cb88.png)

**Comment by harkenn** [comment]
Most of the projects I've worked in both personally and professionally typically close issues as they're fixed, even if that fix is not yet in production. Especially considering how frequently we are updating production, I think that closing issues as they're fixed on development is probably a good pattern to go on. Thoughts @MattColville @cmfcmf ?

**Comment by cmfcmf** [comment]
I like the approach of not closing something until it's live, for two reasons
- it might take a few days to deploy to production (timezones, a bit of testing on the dev server, merging into master)
- other people coming here having the same issue immediately see that it is already being handled

**Comment by harkenn** [comment]
That's typically the argument I've had in the instances where I deviated from my aforementioned "typical" approach. Ultimately I'm not too bothered either way, but it does clutter the issue list and risk leaving something open because someone forgot to add on the `has pr` label or whatnot. The approach of `leave the pr open with the has pr label until its on master (which no individual developer will "know" about without Jerry also announcing everytime he updates the production server` is just process-laden, which development strives to minimize. Process just for process sake is a horrible road to be stuck on and burns out developers.

If we close issues as they're resolved on development, the only significant risk is that a user experiencing the same bug who a) doesn't search for it in the issues list and b) writes it up will have wasted a few minutes of time when a developer responds to their issue as "already fixed in development." Nevermind the fact that this duplicate issue is only a problem if the time it takes to update production is sufficiently large.

If we're updating production every few days (or every week) then that time window is very narrow and the likelyhood of this situation arising very frequently is pretty low. Even if it does arise, though, is it a critical problem? no. At most its a minor annoyance.

The value to cost ratio for this process doesn't work well as soon as you have more than one developer contributing.

**Comment by harkenn** [comment]
sure, that's fine

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!
