### ISSUE TITLE
Add ratings functionality 

### ISSUE THREAD

**Issue by burnhamrobertp** [AdventureLookup/AdventureLookup#16]
Ratings could be left by registered individuals on a per adventure basis. Ratings would be an binary field representing "thumbs up" (1) or "thumbs down" (0). A row for a user on a specific adventure would only exist if they've clicked either thumbs up or thumbs down. Maybe clicking the same option again removes your rating in case you change your mind?

Reviews will be implemented in a separate issue.

**Comment by etchalon** [comment]
Are star values the best way to do this?

I've found "star ratings" to become essentially useless over time, since no one ever agrees on what each increment of the rating means. There's a running joke about their meaning online, "It's either 4.5 stars, or it's garbage".

In my mockups, I went with three boolean values:

1. Have you played this adventure?
2. Would you play it again?
3. Would you recommend it?

It's essentially one step one complicated than just a "Thumbs up, Thumb Down" system.

**Comment by harkenn** [comment]
Can you link to your design in a new issue, for us to be able to refer to in future issues / discussions?

**Comment by etchalon** [comment]
Is a single issue the best way to handle that? I don't use GH issues often, not sure what the standard for a redesign would be.

Public Invision Prototype is here:
https://projects.invisionapp.com/d/main#/projects/11492559/

**Comment by harkenn** [comment]
Yes, its desirable, even though we might break up the design into smaller, more bite-sized chunks, having an issue that contains the overall design is imperitive, lest it be likely to get lost somewhere.

Unfortunately, I can't access that link without being on the invision project. There should be some "Share" functionality to generate a sharable link?

**Comment by etchalon** [comment]
Yep. Sorry, copied the wrong link at first. I edited my comment (but not before you saw it).

**Comment by harkenn** [comment]
I've had the opposite opinion on star or star-like rating systems. I've found that the majority of times, they're a reliable indicator as to the quality/desirability of an item. The most prominent argument, I think, is the fact that a star based rating system is ubiquitous. Most sites that sell items or have listings for movies or media use a rating system like this.

**Comment by etchalon** [comment]
It's a solution many sites have used, yes, but it's also one that's become a running joke in terms of the actual value of the data.

Yes, high rated items (4-5 stars) are generally indicative of overall quality, but if everything below those two ratings are considered garbage by users, what value are those three steps?

I'll defer to Colville's opinion, but I think if Netflix (who developed one of the world's most complex internal scoring projects to try and make star ratings valuable) has ditched it, it's a decent signal that real world use points away from it.

**Comment by harkenn** [comment]
Speaking of Netflix though, have you not been part of any community pertaining to Netflix, or done research on the reaction to the new ratings system? Not only is it easy and plentiful to find "new rating system is horrible" but there are just as many instances on social media, blogs, etc. of "the old rating was great, why was it even changed?"

**Comment by harkenn** [comment]
Paging @MattColville for some input here, when he has the chance.

**Comment by etchalon** [comment]
Yes, people hate new things.

But the change was prompted because NF believed binary data (as you see in YouTube) produced the same input value, with a less complex UI.

**Comment by etchalon** [comment]
My only real complaint about thumbs up / down is that, while reviewing how ratings were used on DM Guild, I noticed quite a few comments / ratings that didn't seem to have anything to do with whether the user would recommend other people play the adventure (which is the only thing that really matters to me).

For a community of DMs looking for adventures, I don't think we need to "rate" adventures, so much as we need to quickly communicate whether people have played a given adventure, and whether they'd recommend you play it. Those two data points are probably sufficient to derive a useful "rating" from.

**Comment by harkenn** [comment]
I found the screens in invision, I like the approach, and I think that leaving text reviews compliments a rating system nicely, but its been my experience that capturing large numbers of user feedback works well when its done with little effort. Ratings being easy to collect and average over a large dataset is what lends to their accuracy.

Implementations with notable "low value ratings" tend to be that way because the dataset is too small (as in less than 10) or too susceptible to gaming (not requiring registration/verification).

**Comment by MattColville** [comment]
There may not be a great solution to this, but I think we can get to good pretty quickly.

There are a couple of issues here I'd like to address;

1: Stars. If thumbs up/thumbs down was good enough for Siskel and Ebert, it's good enough for me. Those guys wanted folks to be able to cut through the bullshit and get an answer to the question "would you recommend this?" Which is exactly what I think we should be doing. And I agree that most folks don't use all five stars anyway. 

Now, there's no way, apart from writing reviews, for customers to know WHY someone voted thumbs up or thumbs down, but that's true no matter the system. Folks could thumbs up something just because they like the author and have never even read the adventure, but we have to rely on a preponderance of the evidence winning the day.

2: How much experience folks have with the adventure. I think we can all imagine an ideal where the votes from folks who've actually run the thing have more weight and while I such a system could be implemented, I just think it's bad bang for buck.

Let folks give the adventures thumbs up/thumbs down, let people write reviews, and we've done plenty.

**Comment by etchalon** [comment]
Done and done. I'll update the UX after I finish these review screens.

**Comment by harkenn** [comment]
Thanks, I've updated the original issue to reflect this!

**Comment by MattColville** [comment]
You guys are awesome.

**Comment by etchalon** [comment]
Updated #21 with Thumbs up / Thumbs down.

**Comment by artyomtrityak** [comment]
Anyone is working on ratings? I'm willing to pick this up

**Comment by burnhamrobertp** [comment]
Not presently, be sure you pull down the local development version so that you're working with the new (yet to be deployed) UI. Once you get your local system running it should resemble dev.adventurelookup.com

**Comment by burnhamrobertp** [comment]
I reviewed the PR, but as far as the functionality goes, the only suggestion I would make is to put the thumbs up/down buttons next to each other. Its highly unusual UX for them to be so separate.

**Comment by cmfcmf** [comment]
This is now live :tada:
