### ISSUE TITLE
How to handle the adventure's author / rights holders

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#172]
I've received an email by the author and/or rightsholder of an adventure, asking whether they could be made 'owner' of their adventures to be able to edit wrong information without the need for change requests. Is this something we want? If yes, would we still want the original person who entered the adventure into ADL be able to edit it? @MattColville

**Comment by MattColville** [comment]
Well, how hard is it to let the dude edit the adventure?

I mean, I've seen change requests where almost everything in the record was wrong, and it maybe took me five minutes to fix it, so it's not like the current system is a huge pain in the ass. I think the author could just submit changes like anyone else.

And it's not like the adventure is going to change over time so that someone's going to need to maintain it.

**Comment by cmfcmf** [comment]
Closing this - the authors can very well submit change requests. The same rules apply, if they submit many adventures and/or change requests, they can apply for curator status.
