### ISSUE TITLE
Collapsible Profile Lists

### ISSUE THREAD

**Issue by WillSave** [AdventureLookup/AdventureLookup#224]
As I create more and more modules, my scrolling gets longer to see if I have any unresolved issues. It would be nice if these were subheadings that begin collapsed but then could be expanded: Your Modules, Unresolved Issues, Resolved Issues (and any other sections that would be helpful).

**Comment by marcellarius** [comment]
A very simple solution would be to use a two column layout (trivial to do in Bootstrap), or to put the unresolved issues list at the top of the page.

**Comment by iwatts** [comment]
It might be nice to handle some of the lengthy scrolling with a "Scroll to Top" button.

**Comment by cmfcmf** [comment]
Hey @WillSave, @marcellarius, @iwatts, I know it's been a while, but I finally managed to implement your suggestion. I've included a screen shot in the pull request: https://github.com/AdventureLookup/AdventureLookup/pull/274 Let me know if you have any feedback.

I've opted for not using a two column layout, because I felt like having only half as much space didn't look too good.
