### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by levi-blodgett** [AdventureLookup/AdventureLookup#241]
Hello, new to this and trying to set up properly, once I am I'm planning on putting in search features for the checkboxes on all of the filters so things like monsters aren't such heinously long lists. I'll probably just use JavaScript to do so.

I took a screenshot of my error and am posting it below:

![error](https://user-images.githubusercontent.com/31705508/31970506-65f49bb0-b8d5-11e7-818d-539ea90b7cea.jpg)

I went through each steps exactly, and then installed symfony via npm, and it gave me this error.

Additionally, when I do this from the readme:

Start webpack to watch changes to assets and recompile them
Can be run inside the virtual machine or outside of the virtual machine
If run inside the virtual machine:
npm run dev-server-guest

I get this error:

![error1](https://user-images.githubusercontent.com/31705508/31978335-285c25a6-b8fe-11e7-9927-e0f92f33cff7.png)

**Comment by burnhamrobertp** [comment]
The manifest error will occur anytime you view the application but the front end (FE) process hasn't finished or isn't running correctly (as you identified in your second screenshot).

As to the actual problem (the second screenshot), you can see in the terminal output `sh: 1: encore: not found` which is the actual error. NPM is pretty good about detecting the fact that nothing is going wrong with its internal scripts (which is why it says "this is probably not a problem with npm") so you need to scour above the npm error messages for some other output.

In this case, you either don't have encore installed or it can't find it. Make sure you've run `npm i` and that you are running the `npm run dev...` command from the same place as you ran `npm i`. I personally installed the FE dependencies in Windows, so I would use `npm run dev-server-host` in a terminal in windows.
