### ISSUE TITLE
Linkable search results

### ISSUE THREAD

**Issue by natefinch** [AdventureLookup/AdventureLookup#249]
I want to be able to link people to specific result sets based on filters and search terms, but the URL doesn't reflect the inputs to the system, so I can't.  This is a pretty important UX for most people, I think.

**Comment by j-frost** [comment]
I agree. Let me get on that.

**Comment by cmfcmf** [comment]
Nice @j-frost! I've added the `in progress` label, because you're working on it.
The JavaScript/HTML/Twig handling the search form is quite a mess at the moment. 
Feel free to change that as you see fit (previously we also thought about pulling in a framework like React or Vue.js, but never got around to do it. If it makes things easier for you, go ahead).

**Comment by j-frost** [comment]
You know I thought about this quite a lot, @cmfcmf. 

Right now I'm thinking SPA via Angular, and that seems like quite a huge change to the code base. Also I don't know if you guys are even OK with Angular as a technology. I know a lot of people who like React  kinda hate Angular. Personally, I think it would be a great fit for the project. 

For this particular feature I think the effort required to introduce any framework (but especially any opinionated ones like Angular) is way out of scope. I see all back end functionality already exists anyway, so for now, I think I'll conform to the current structure and "hack" it a little bit. 

Feel free to share your ideas on what tech to use for the front end. Or do we have no direction just yet?

Also: Could/Should I have added those labels? From here it looks like I can't change them, is that the case? Anyways, thanks for that :)

**Comment by burnhamrobertp** [comment]
I personally have a lot of experience in React and have mixed reviews from coworkers on angular. A couple of people really dislike it, and a couple of people have told me "it works." If / when we move to a front end app decoupled from the back end, I would prefer React...but take that for what its worth coming from only one of a number of contributors.

**Comment by j-frost** [comment]
Guess I'm torn on this. 'This' being the "framework vs library" discussion. 

The warning I've heard about React is that it's not much more than a view library; and that it doesn't solve the notorious problems of JavaScript. Those being a large number of pitfalls that new or inexperienced developers will fall into and make development both slow and painful. I guess this would be true of Vue as well.

Angular, on the other hand, has been presented to me as an "actual" (whatever that means) framework. I've found it to be quite opinionated while working with it, but I've also found it quite easy to buy into. The obvious advantage being that when a certain structure is mandated, you can't roll your own and fuck it up. 

I really don't like these kinds of discussions though. And I'm usually the first to philosophize. Honestly, if we have an experienced React developer on board in @burnhamrobertp, I'm sure it'll work out great. And it's not like React itself doesn't have a few advantages. I think it might make the transition a lot easier because MPAs are way easier to implement. 

Are you interested in providing something like a proof of concept, @burnhamrobertp? I'd really like to learn how to "properly" do React :)

**Comment by natefinch** [comment]
So, this seems like a discussion that is way beyond the scope of the bug. The simplest fix is to parse parameters in the URL for setting filter values, and then to update the URL to represent the filters chosen in the UI.   Using angular or react for that seems like WAY more work than doing something a lot more simple.  That's an architectural change.  I think this can be done more simply.

Granted, I'm not a web dev in my day job, but I've done enough to be dangerous ;)

**Comment by j-frost** [comment]
So true, @natefinch. Which is why I said I was going to hack it instead. I just didn't want to stifle a conversation that's gonna have to happen sooner or later.

**Comment by cmfcmf** [comment]
Sorry - I didn't intend to derail this ticket into a JS framework discussion. I mainly wanted to make clear we weren't _opposed_ to introducing something like React/Angular/Vue etc.

**Comment by j-frost** [comment]
So I started work on this, and I didn't want to do everything from scratch, so I tried out this npm package called 'query-string-manipulator'. It has a bug though, so if this [issue](https://github.com/BerryCloud/js-query-string-manipulator/issues/1) isn't resolved quickly, I'll just build it myself. 

Also, I've realized that of the number inputs both max and min need to be set. What do you guys think: Should I just input sane defaults (like 0 and MAX_VAL) if the user hasn't yet set anything or would you rather I change the back end to accept queries without one or the other border value set?

**Comment by cmfcmf** [comment]
> Also, I've realized that of the number inputs both max and min need to be set. What do you guys think: Should I just input sane defaults (like 0 and MAX_VAL) if the user hasn't yet set anything or would you rather I change the back end to accept queries without one or the other border value set?

I'm unsure what you mean here. When going to https://dev.adventurelookup.com/adventures/, I'm able to type in `345` as min length and it lets me search without a max length being set.

> So I don't know how you guys do things around here -- I'm used to pull requests being opened fairly early and discussion taking place there.
> 
> If you think I'm doing it wrong, please don't hesitate to tell me.

No, that's great! I'm all for opening pull requests as soon as there is something working 👍 I usually prepend a `WIP:` or `[WIP]` to the title to make sure they are marked as work in progress and not merged until finished. This way you give people the chance to comment and give feedback early on.

**Comment by j-frost** [comment]
Alright, changed the pr title for now. 

The min/max thing is in reference to what you found in the code too, @cmfcmf, at https://github.com/AdventureLookup/AdventureLookup/pull/259#discussion_r173213593.
