### ISSUE TITLE
Forgot password functionality

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#31]
There currently is no way to recover a lost password.
Implementing such a functionality would require emailing to be setup.

**Comment by etchalon** [comment]
We can use my companies' Postmark account for this. I'll happily cover the credits. We'd just need to work with @JohnnyFlash and @MattColville to authenticate Postmark and add the SPF records.

**Comment by etchalon** [comment]
Though this reminds me that I need to design that screen in #21, as well as a "Profile" page for users.

**Comment by harkenn** [comment]
Technically you can use the local smtp configuration for the unix server hosting the site. You just need to setup an MX record on the host and do some basic configuration on the smtp server. Non-spam recipient rate won't be as good as smtp2go or postmark, because there is no existing server reputation, but it'll work for a wide number of people. Worst-case is they have to go checking their spam/junk mail for the e-mail.

**Comment by etchalon** [comment]
Eh. Postmark is insanely cheap, has higher deliverability guarantees, easier to access logging and does not require any local SMTP/sendmail configuration. The only downside is the cost, which I'll happily cover.

**Comment by harkenn** [comment]
Using a service is fine with me!

**Comment by harkenn** [comment]
Development side of things can test this using mailtrap.io, potentially. Once this functionality is done and ready to go out to production, @etchalon you'll have to coordinate with Jerry to get him the settings he needs to put into the production systems' env variables (or wherever).

**Comment by JohnnyFlash** [comment]
There is an SMTP relay on the local network of the production server.  I already put the settings in the  parameters.yml

**Comment by cmfcmf** [comment]
Pull request in #168. Leaving this issue open until it's merged and deployed to the live site.

**Comment by cmfcmf** [comment]
This is now live at https://adventurelookup.com!
