### ISSUE TITLE
Improve page footer design

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#321]
The footer looks off, mainly because the text is directly on top of the gray page background. 
The obvious solution would be to also give it a white background like the other content containers, but I feel like that would be distracting.
Maybe we could give it a dark background (like the search filters) that spans the entire width of the page?
Not sure about what's best. If you have any ideas, leave them below :point_down:

**Comment by wetterlicht** [comment]
I took some time to play around a bit with the existing color palette. I think this looks pretty good but maybe the dark background makes it a bit too prominent? A bit hard to judge because now my focus is always drawn to the footer anyway. Could try one of the lighter greys but at that point the coral links would be a bit hard to read.

<img width="957" alt="footer" src="https://user-images.githubusercontent.com/9221797/82832709-28933e00-9ebc-11ea-8b95-52bf52d6902b.png">

**Comment by cmfcmf** [comment]
I think that looks alright - especially if combined with a dramatically improved margin between content (e.g., the load more results button) and the footer. But I'm also really bad when it comes to design, so I can't really imagine other possibilities.


> Could try one of the lighter greys but at that point the coral links would be a bit hard to read.

I think readability is important.
