### ISSUE TITLE
The 'ADVENTURE LOOKUP' button at the top of the startpage is not fully clickable

### ISSUE THREAD

**Issue by cmfcmf** [AdventureLookup/AdventureLookup#329]
![image](https://user-images.githubusercontent.com/2145092/82231766-eef78b80-992d-11ea-92f8-1443ea646ecc.png)

Only the lower half of that orange button is clickable, while the upper half is not. It would be great if the whole button was clickable. Tested in Chrome.

**Comment by Wigginns** [comment]
Firefox and Edge behave the same. However, if the page width is small enough to push the filter bar above the results it's fully clickable. 
![image](https://user-images.githubusercontent.com/3180645/82236285-1e3bd780-98f1-11ea-9cf1-9d8162734668.png)

**Comment by mattfelten** [comment]
I can fix this. Can you give me a bit to set up the dev environment?

**Comment by cmfcmf** [comment]
> I can fix this. Can you give me a bit to set up the dev environment?

Of course! Please also give us feedback if you run into issues while setting up your dev environment. We tried to make that process as easy as possible, so please tell us if anything doesn't work as expected or could be documented better.

**Comment by mattfelten** [comment]
Just submitted a PR for this issue.

---

I did have some minor trouble setting the project up. The instructions say I only needed to install Vagrant and Docker (on OSX) but when I tried to `vagrant ssh` in, it was complaining about me not having VirtualBox installed.

```
$ vagrant ssh
Vagrant failed to initialize at a very early stage:

The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

If you're on Windows and just installed VirtualBox, you have to
log out and log back in for the new environmental variables to take
effect. If you're on Linux or Mac, verify your PATH contains the folder
that has VBoxManage in it.
```

That's weird because I provisioned with Docker... Once I installed VirtualBox, everything worked fine again. I'm wondering if I had VirtualBox installed previously on here (pretty sure I did), and didn't uninstall correctly (also probable), so it thought it was here, tried to use it, but it wasn't. 🤷‍♂️

---

Separate question, I'm new to Vagrant/Docker. Is there anything I should be doing to shut down the local server when I'm done?

**Comment by cmfcmf** [comment]
> I did have some minor trouble setting the project up. The instructions say I only needed to install Vagrant and Docker (on OSX) but when I tried to `vagrant ssh` in, it was complaining about me not having VirtualBox installed.
> That's weird because I provisioned with Docker... Once I installed VirtualBox, everything worked fine again. I'm wondering if I had VirtualBox installed previously on here (pretty sure I did), and didn't uninstall correctly (also probable), so it thought it was here, tried to use it, but it wasn't. man_shrugging

That is odd :confused: I'm afraid I can't really reproduce that since I never ran into that sort of problem.

> Separate question, I'm new to Vagrant/Docker. Is there anything I should be doing to shut down the local server when I'm done?

You can run `vagrant halt` which will shutdown the VM / stop the container. It's probably more important to run that when using a VirtualBox VM, but it'll never hurt :)
