### ISSUE TITLE
Add a play length filter

### ISSUE THREAD

**Issue by idiot-sandwich** [AdventureLookup/AdventureLookup#37]
DMs often are looking for an adventure that they can run in X number of sessions, esp. one shots. An filter for how long an adventure takes to run (in hours, sessions, or a category indication) would be very useful to me. Next time multiple players cancel, I hope to find a one shot very quickly. :-)

**Comment by etchalon** [comment]
Adventures designed to be played in one setting are probably easy to discern, but I feel like any estimation on "# of sessions required" is going to be wildly different between parties.

I'd say a "One-Shot" boolean might be useful, but not a "Play Length" field. 

What say you, good king @MattColville ?

**Comment by harkenn** [comment]
The number of pages is a reasonable estimation for this though, isn't it? One shots being less than 10 or 15 pages?

**Comment by etchalon** [comment]
True. Maybe a "Less than page count" filter is enough. We already have the data for it.

**Comment by MattColville** [comment]
I don't see how a Play Length field would work, since there's no way to tell how many sessions an adventure will take.

A One-shot boolean isn't bad, but it would be hugely misleading. Lots of short Dungeon adventures are no where labeled "one shot" but they certainly are, some of them are only one encounter!

So I think the current page count functionality covers us better than a Play Length field.

Can users search for "less than 10 pages?"

**Comment by harkenn** [comment]
Yes, the current implementation for filtering by Length allows you to do this:

![image](https://user-images.githubusercontent.com/231052/28350331-f18450e0-6c0d-11e7-9f94-7f0c7b4704fc.png)

So that's adventures with a max length of 25 pages, for example. You could type in "10" there and it would find all adventures with <= 10 pages. This screenshot taken from production:

![image](https://user-images.githubusercontent.com/231052/28350379-33675a7a-6c0e-11e7-983a-71a73ad7b9ea.png)

Cursory spot check indicates all of the returned adventures have a page length less than 10.

**Comment by harkenn** [comment]
Closing this as wont-fix. This functionality is as closely mirrored as we're going to get for the foreseeable future in "page length".

**Comment by idiot-sandwich** [comment]
Ok, clear. Thanks for the clear answer, quick response and awesome work.
