### ISSUE TITLE
I'd like to be able to edit the list of entities

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#59]
I assume I'm using this terminology correctly. The things that can populate a field within a record.

Right now people can add Orc and Orcs and while that isn't the end of the world, it bugs me. :D The search should return Orc result for Orcs and vice versa.

But more to the point, people can stick things in there, like Waterdeep for Setting, and then other people will think "Oh this Forgotten Realms adventure should be a Waterdeep adventure" and that is no bueno.

This functionality may already exist in an admin panel I do not wot of.

**Comment by harkenn** [comment]
The EasyAdmin panel might be able to be configured to expose this data to make it available to you pretty easy (add/remove without having to wait for a developer or anything like that).

**Comment by MattColville** [comment]
If I understand the EasyAdmin panel, right now it can't do this. It has a big Approve/Disapprove button, but without being able to see the actual fields and entities, I have no idea if anything should be approved.

**Comment by cmfcmf** [comment]
> If I understand the EasyAdmin panel, right now it can't do this.

Correct. It is not yet configured correctly for you to be able to do it. 

On a related note: As I understand, you, for example, don't want users to add any *environment* they like to a new adventure, to keep the list of environments clean and concise (and to avoid "hills", for example). In contrary, you probably don't want to predefine a list of authors a user can choose from, because there is no way we know all the authors beforehand.
Could you @MattColville please confirm for which of these entities you want users to be able to add new options and for which you only want them to be able to select from what's already predefined? 

- [ ] monsters
- [ ] items
- [ ] npcs
- [ ] authors
- [ ] environments
- [ ] edition
- [ ] publisher
- [ ] setting

**Comment by MattColville** [comment]
I think even for the stuff that's predefined, folks should be able to submit new ones, but it should require approval. 

Like for environment, I didn't think of "ship" but it should definitely be an environment. "Are there any good adventures set on a ship?" Is a super common question. Likewise "tower" or "castle."

**Comment by harkenn** [comment]
Initially that circumstance would probably need to be handled manually by someone leaving a comment to making a reddit post, but in the next version we can look to add the ability for environments to be added but require approval.
